Programacao_Visual/Semana08/S081_Slides/TP11/Models/ErrorViewModel.cs
using System;

namespace TP11.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Programacao_Visual/Semana08/S081_Slides/TP11/Models/Foto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TP11.Models
{
    public class Foto
    {
        public String Codigo { get; set; }
        public String Titulo { get; set; }
    }
}

Programacao_Visual/Semana08/S081_Slides/TP11/Controllers/FotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TP11.Models;

namespace TP11.Controllers
{
    public class FotoController : Controller
    {
        public IActionResult Index()
        {
            Foto f = new Foto() { Codigo = "ABC000001", Titulo = "Deserto" };
            return View(f);
        }
    }
}

Programacao_Visual/Semana08/S081_Slides/TP11/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TP11.Models;

namespace TP11.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Contactos()
        {
            return View();
        }

        public IActionResult ContSemScaff()
        {
            return View();
        }

    }
}

Programacao_Visual/Semana08/S081_Slides/TP11/Controllers/MusicaDoDiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TP11.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TP11.Controllers
{
    public class MusicaDoDiaController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            Foto f = new Foto() { Codigo = "ABC000001", Titulo = "Deserto" };
            return View(f);
        }
    }
}

Programacao_Visual/Semana08/S081_Slides/TP11/Views/Foto/Index.cshtml
@model TP11.Models.Foto

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<div>
    <h4>Foto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
    </dl>
</div>

Programacao_Visual/Semana08/S081_Slides/TP11/Views/Home/ContSemScaff.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Cont Sem Scaff";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Contactos Sem Scaff</h1>

<address>
    FotosShopping Inc.<br />
    Rua das Fotos, nº1<br />
    2815-Imagem de Marca<br />
    Portugal<br />
    <abbr title="Phone">P:</abbr>
    210795000
</address>

Programacao_Visual/Semana08/S081_Slides/TP11/Views/Home/Contactos.cshtml
@{
    ViewData["Title"] = "Contactos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Contactos</h1>

<address>
    FotosShopping Inc.<br />
    Rua das Fotos, nº1<br />
    2815-Imagem de Marca<br />
    Portugal<br />
    <abbr title="Phone">P:</abbr>
    210795000
</address>

Programacao_Visual/Semana08/S081_Slides/TP11/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <div class="text-center">
        <h1 class="display-4">Seja Bem Vindo</h1>
        <p>Aqui vai encontrar as melhores imagens para o seu site</p>
        <img src="~/images/UnderConstruction.jpg" />
    </div>

Programacao_Visual/Semana08/S081_Slides/TP11/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FotoShopping</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FotoShopping</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <!-- <a class="<formatação da css>"
        asp-area="<Area de paginas geradas por scaffolding>"
        asp-controller="<Nome do conttrolador onde está a ação"
        asp-action="nome da ação">Texto do Link</a>-->
                            <a class="nav-link text-dark"
                               asp-area=""
                               asp-controller="Home"
                               asp-action="Contactos">Contactos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ContSemScaff">ContSemScaff</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Foto" asp-action="Index">Foto do Dia</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - FotoShopping - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>